INSERT INTO main_banco(id, nombre) VALUES(1, 'Banco Crédito e Inversiones BCI');
INSERT INTO main_banco(id, nombre) VALUES(2, 'Banco de Chile');
INSERT INTO main_banco(id, nombre) VALUES(3, 'Banco del Desarrollo');
INSERT INTO main_banco(id, nombre) VALUES(4, 'Banco Estado');
INSERT INTO main_banco(id, nombre) VALUES(5, 'Banco Falabella');
INSERT INTO main_banco(id, nombre) VALUES(6, 'Banco Itaú');
INSERT INTO main_banco(id, nombre) VALUES(7, 'Banco Internacional');
INSERT INTO main_banco(id, nombre) VALUES(8, 'Banco Ripley');
INSERT INTO main_banco(id, nombre) VALUES(9, 'Banco Santander Santiago');
INSERT INTO main_banco(id, nombre) VALUES(10, 'Banco Security');
INSERT INTO main_banco(id, nombre) VALUES(11, 'Bice');
INSERT INTO main_banco(id, nombre) VALUES(12, 'Consorcio');
INSERT INTO main_banco(id, nombre) VALUES(13, 'Corp Banca');
INSERT INTO main_banco(id, nombre) VALUES(14, 'Rabobank');
INSERT INTO main_banco(id, nombre) VALUES(15, 'Scotiabank');
INSERT INTO main_banco(id, nombre) VALUES(16, 'HSBC Bank');
